### ISSUE TITLE
Creating a separate object from the main `Workflow` for SAS/PGE purposes

### ISSUE THREAD

**Issue by scottstanie** [opera-adt/dolphin#61]
There needs to be a new YAML interface for SDS which looks something like this:

```yaml 
runconfig:
  name:
  groups:
    pge_name_group:
        pge_name:

    input_file_group:
      input_file_path:
    dynamic_ancillary_file_group:
        ....
      *algorithm_parameters*:
    primary_executable:
      product_type:

    product_path_group:
      product_path:
      scratch_path:
      sas_output_path:
      product_version:

    log_file:
```

where `algorithm_parameters` has the rest of the things in the current `Workflow`.

Current plan: make a new separate `SasWorkflow` which contains (probably easier than subclassing) the `Workflow`, then has more custom logic for going to/from YAML.
